package server

import (
	"errors"
	"io"
	"net/http"

	"github.com/google/uuid"
	"github.com/gorilla/mux"
	"gorm.io/gorm"

	"github.com/ya-breeze/healthvault/pkg/database"
)

// contentTypeForExt maps a photo's stored extension back to a response
// Content-Type. Extensions are server-generated by storage.DetectFormat, so
// this is an exhaustive switch, not a sniff.
func contentTypeForExt(ext string) string {
	switch ext {
	case "jpg":
		return "image/jpeg"
	case "png":
		return "image/png"
	case "webp":
		return "image/webp"
	default:
		return "application/octet-stream"
	}
}

// servePhoto streams the photo at relPath, or 404s if relPath is empty (the
// owning record exists but has no photo — a manual meal, most commonly).
func (h *foodHandlers) servePhoto(w http.ResponseWriter, relPath string) {
	if relPath == "" {
		http.Error(w, "not found", http.StatusNotFound)
		return
	}
	f, err := h.photos.Open(relPath)
	if err != nil {
		http.Error(w, "not found", http.StatusNotFound)
		return
	}
	defer f.Close() //nolint:errcheck

	ext := ""
	for i := len(relPath) - 1; i >= 0 && relPath[i] != '.'; i-- {
		ext = string(relPath[i]) + ext
	}
	w.Header().Set("Content-Type", contentTypeForExt(ext))
	io.Copy(w, f) //nolint:errcheck
}

// MealPhoto handles GET /api/food/meals/{id}/photo, owner-scoped.
func (h *foodHandlers) MealPhoto(w http.ResponseWriter, r *http.Request) {
	claims := ClaimsFromCtx(r)
	if claims == nil {
		http.Error(w, "unauthorized", http.StatusUnauthorized)
		return
	}
	id, err := uuid.Parse(mux.Vars(r)["id"])
	if err != nil {
		http.Error(w, "invalid id", http.StatusBadRequest)
		return
	}

	var meal database.FoodMeal
	err = h.storage.DB().Select("photo_path").
		Where("id = ? AND user_id = ?", id, claims.UserID).First(&meal).Error
	if errors.Is(err, gorm.ErrRecordNotFound) {
		http.Error(w, "not found", http.StatusNotFound)
		return
	}
	if err != nil {
		http.Error(w, "query error", http.StatusInternalServerError)
		return
	}
	h.servePhoto(w, meal.PhotoPath)
}

// CalibrationSamplePhoto handles GET /api/food/calibration-samples/{id}/photo, owner-scoped.
func (h *foodHandlers) CalibrationSamplePhoto(w http.ResponseWriter, r *http.Request) {
	claims := ClaimsFromCtx(r)
	if claims == nil {
		http.Error(w, "unauthorized", http.StatusUnauthorized)
		return
	}
	id, err := uuid.Parse(mux.Vars(r)["id"])
	if err != nil {
		http.Error(w, "invalid id", http.StatusBadRequest)
		return
	}

	var sample database.FoodCalibrationSample
	err = h.storage.DB().Select("photo_path").
		Where("id = ? AND user_id = ?", id, claims.UserID).First(&sample).Error
	if errors.Is(err, gorm.ErrRecordNotFound) {
		http.Error(w, "not found", http.StatusNotFound)
		return
	}
	if err != nil {
		http.Error(w, "query error", http.StatusInternalServerError)
		return
	}
	h.servePhoto(w, sample.PhotoPath)
}
