package hcimport

var sleepStageNames = map[int]string{
	1: "awake_in_bed",
	2: "sleeping",
	3: "awake",
	4: "out_of_bed",
	5: "light",
	6: "deep",
	7: "rem",
}

var exerciseTypeNames = map[int]string{
	2:   "back_extension",
	4:   "biking",
	5:   "biking_stationary",
	6:   "boot_camp",
	7:   "boxing",
	8:   "calisthenics",
	9:   "circuit_training",
	10:  "cricket",
	11:  "cross_country_skiing",
	12:  "cross_fit",
	13:  "curling",
	14:  "dancing",
	15:  "deadlift",
	16:  "dumbbell_curl_right_arm",
	17:  "dumbbell_curl_left_arm",
	18:  "dumbbell_front_raise",
	19:  "dumbbell_lateral_raise",
	20:  "dumbbell_triceps_extension_left_arm",
	21:  "dumbbell_triceps_extension_right_arm",
	22:  "dumbbell_triceps_extension_two_arm",
	23:  "elliptical",
	24:  "exercise_class",
	25:  "fencing",
	26:  "frisbee_disc",
	27:  "football_american",
	28:  "football_australian",
	29:  "forward_twist",
	30:  "golf",
	31:  "guided_breathing",
	32:  "gymnastics",
	33:  "running",
	34:  "handball",
	35:  "high_intensity_interval_training",
	36:  "hiking",
	37:  "ice_hockey",
	38:  "ice_skating",
	39:  "jump_rope",
	40:  "jumping_jack",
	41:  "lat_pull_down",
	42:  "lunge",
	43:  "martial_arts",
	44:  "meditation",
	45:  "paddling",
	46:  "para_gliding",
	47:  "pilates",
	48:  "plank",
	49:  "racquetball",
	50:  "rock_climbing",
	51:  "roller_hockey",
	52:  "rowing",
	53:  "walking",
	54:  "running_treadmill",
	55:  "sailing",
	56:  "scuba_diving",
	57:  "skiing",
	58:  "yoga",
	59:  "snowboarding",
	60:  "snowshoeing",
	61:  "soccer",
	62:  "softball",
	63:  "squash",
	64:  "squat",
	65:  "stair_climbing",
	66:  "stair_climbing_machine",
	67:  "strength_training",
	68:  "stretching",
	69:  "surfing",
	70:  "swimming_open_water",
	71:  "swimming_pool",
	72:  "table_tennis",
	73:  "tennis",
	74:  "upper_twist",
	75:  "volleyball",
	76:  "walking_treadmill",
	77:  "water_polo",
	78:  "weightlifting",
	79:  "wheelchair",
	80:  "windsurfing",
	81:  "yoga_bicycling",
	82:  "biathlon",
	83:  "obstacle_course",
	84:  "para_biking",
	85:  "para_rowing",
	86:  "para_swimming",
	87:  "para_table_tennis",
	88:  "para_tennis",
	89:  "para_triathlon",
	90:  "para_wheelchair_racing",
	91:  "triathlon",
	92:  "orienteering",
	93:  "cricket_bowling",
	94:  "cricket_batting",
	95:  "cricket_fielding",
}

func sleepStageName(code int) string {
	if name, ok := sleepStageNames[code]; ok {
		return name
	}
	return "unknown"
}

func exerciseTypeName(code int) string {
	if name, ok := exerciseTypeNames[code]; ok {
		return name
	}
	return "unknown"
}
