// Package storage saves meal and calibration photos to local disk.
//
// Every stored path is generated by the server from the owning IDs. The
// client-supplied filename is never used in any path component, so path
// traversal is not reachable here by construction.
package storage

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/google/uuid"
)

// Owner kinds, used as a path segment.
const (
	OwnerMeal        = "meal"
	OwnerCalibration = "calibration"
)

// Image formats we accept. This is deliberately the intersection of what we can
// store and what the vision provider accepts: storing a format the model cannot
// read would let a photo pass validation and then fail analysis and every retry,
// stranding its meal in `failed` permanently.
const (
	FormatJPEG = "jpg"
	FormatPNG  = "png"
	FormatWebP = "webp"
)

var (
	// ErrTooLarge means the upload exceeded the configured byte limit.
	ErrTooLarge = errors.New("upload exceeds maximum size")
	// ErrUnsupportedFormat means the content is not an image we accept.
	ErrUnsupportedFormat = errors.New("unsupported image format")
	// ErrHEIC is a distinct case so callers can return an actionable message.
	// HEIC is the iPhone camera default, so a generic error here is a bad
	// experience for the single most common upload path.
	ErrHEIC = errors.New("HEIC images are not supported")
)

// DetectFormat identifies the image type from its content. The declared
// Content-Type and the filename are both untrusted and play no part.
//
// Go's http.DetectContentType handles JPEG/PNG/WebP but does not recognize
// HEIC at all, so HEIC is matched explicitly via its ISO-BMFF brand purely so
// that it can be rejected by name rather than as "not an image".
func DetectFormat(b []byte) (string, error) {
	switch {
	case len(b) >= 3 && bytes.Equal(b[:3], []byte{0xFF, 0xD8, 0xFF}):
		return FormatJPEG, nil
	case len(b) >= 8 && bytes.Equal(b[:8], []byte{0x89, 'P', 'N', 'G', 0x0D, 0x0A, 0x1A, 0x0A}):
		return FormatPNG, nil
	case len(b) >= 12 && bytes.Equal(b[:4], []byte("RIFF")) && bytes.Equal(b[8:12], []byte("WEBP")):
		return FormatWebP, nil
	case isHEIC(b):
		return "", ErrHEIC
	default:
		return "", ErrUnsupportedFormat
	}
}

// isHEIC checks for an ISO base media file with a HEIF brand.
func isHEIC(b []byte) bool {
	if len(b) < 12 || !bytes.Equal(b[4:8], []byte("ftyp")) {
		return false
	}
	switch string(b[8:12]) {
	case "heic", "heix", "heim", "heis", "hevc", "hevx", "mif1", "msf1":
		return true
	}
	return false
}

// Store is a rooted photo store.
type Store struct {
	root string
}

// New returns a Store rooted at dir.
func New(dir string) *Store { return &Store{root: dir} }

// RelPath is the server-generated location for an owner's photo, relative to
// the store root: {user_id}/{owner_kind}/{owner_id}.{ext}
func RelPath(userID uuid.UUID, ownerKind string, ownerID uuid.UUID, ext string) string {
	return filepath.Join(userID.String(), ownerKind, ownerID.String()+"."+ext)
}

// Save validates and writes an upload, returning the stored relative path.
// It reads at most maxBytes+1 so an oversized body is rejected without being
// buffered in full.
func (s *Store) Save(r io.Reader, maxBytes int64, userID uuid.UUID, ownerKind string, ownerID uuid.UUID) (string, error) {
	data, err := io.ReadAll(io.LimitReader(r, maxBytes+1))
	if err != nil {
		return "", fmt.Errorf("read upload: %w", err)
	}
	if int64(len(data)) > maxBytes {
		return "", ErrTooLarge
	}
	ext, err := DetectFormat(data)
	if err != nil {
		return "", err
	}

	rel := RelPath(userID, ownerKind, ownerID, ext)
	abs := filepath.Join(s.root, rel)
	if err := os.MkdirAll(filepath.Dir(abs), 0o750); err != nil {
		return "", fmt.Errorf("create photo dir: %w", err)
	}
	if err := os.WriteFile(abs, data, 0o640); err != nil {
		return "", fmt.Errorf("write photo: %w", err)
	}
	return rel, nil
}

// Open returns a reader for a stored photo.
func (s *Store) Open(rel string) (*os.File, error) {
	f, err := os.Open(filepath.Join(s.root, rel)) //nolint:gosec // rel is server-generated
	if err != nil {
		return nil, fmt.Errorf("open photo: %w", err)
	}
	return f, nil
}

// Read returns the bytes of a stored photo, for re-analysis and calibration runs.
func (s *Store) Read(rel string) ([]byte, error) {
	b, err := os.ReadFile(filepath.Join(s.root, rel)) //nolint:gosec // rel is server-generated
	if err != nil {
		return nil, fmt.Errorf("read photo: %w", err)
	}
	return b, nil
}

// Remove deletes a stored photo. A photo that is already gone is not an error:
// deleting the owning record must still succeed.
func (s *Store) Remove(rel string) error {
	if rel == "" {
		return nil
	}
	if err := os.Remove(filepath.Join(s.root, rel)); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("remove photo: %w", err)
	}
	return nil
}
